do {

    try canThrowAnError()

    // no error was thrown

} catch {

    // an error was thrown

}